apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-env-secrets
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-secret-like-env-vars
      match:
        any:
        - resources:
            kinds: ["Deployment","StatefulSet","DaemonSet","Job","CronJob","Pod"]
      # NOTE: Trivy cluster scanning creates temporary jobs in the 'trivy-temp' namespace
      # with environment variables that match secret-like patterns (e.g., PATH, LD_LIBRARY_PATH).
      # We exempt these system namespaces to allow Trivy vulnerability scanning to work.
      # Application workloads in user namespaces remain protected by this policy.
      preconditions:
        all:
        - key: "{{ request.namespace }}"
          operator: NotIn
          value:
          - trivy-temp
          - kube-system
          - kube-node-lease
          - kube-public
      validate:
        message: "Environment variables may not contain secret-like keys (PASSWORD, TOKEN, KEY, SECRET, API_KEY, ACCESS_KEY)."
        pattern:
          spec:
            containers:
              - env:
                  - name: "!/(?i).*(password|token|secret|api[_-]?key|access[_-]?key).*/"
