apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-user
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: require-nonroot
      match:
        resources:
          kinds: ["Pod"]
      validate:
        message: "Containers must not run as root (runAsNonRoot: true)"
        anyPattern:
          - spec:
              securityContext:
                runAsNonRoot: true
          - spec:
              containers:
              - =(securityContext):
                  =(runAsUser): ">0"
